version = 1

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "angularjs"
  ]

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true